# Generated by Django 5.1.6 on 2025-02-23 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('school', models.CharField(max_length=200)),
                ('student_class', models.CharField(max_length=50)),
                ('guardian_phone', models.CharField(max_length=15)),
                ('annual_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_sponsored', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SponsorSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sponsor_name', models.CharField(max_length=100)),
                ('sponsor_email', models.EmailField(max_length=254)),
                ('date_selected', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.studentapplication')),
            ],
        ),
    ]
