# Generated by Django 5.1.6 on 2025-03-17 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_studentapplication_supportive_documents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentapplication',
            name='name',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='studentapplication',
            name='school',
            field=models.TextField(max_length=200),
        ),
    ]
